export const Game = {
    QUARTERS: 4,
    QUARTER_LENGTH_SECONDS: 12 * 60,
    OVERTIME_LENGTH_SECONDS: 5 * 60,
    SHOT_CLOCK_SECONDS: 24,
    POSSESSIONS_PER_GAME: 100,
} as const;

export const SHOT_TYPES = {
    PROB_TWO_POINT_ATTEMPT: 0.45,
    PROB_THREE_POINT_ATTEMPT: 0.25,
    PROB_FREE_THROW_TRIP: 0.15,
    PROB_SHOT_CLOCK_VIOLATION: 0.02,
    PROB_TURNOVER: 0.13,

    BASE_TWO_POINT_PCT: 0.45,
    BASE_THREE_POINT_PCT: 0.35,
    BASE_FREE_THROW_PCT: 0.75,

    OPEN_SHOT_BONUS: 0.05,
    CONTESTED_SHOT_PENALTY: -0.05,
} as const;

export const RATING_SCALE = {
    SHOOTING_TWO_WEIGHT: 0.28,
    SHOOTING_THREE_WEIGHT: 0.22,
    FINISHING_WEIGHT: 0.15,
    PASSING_TURNOVER_WEIGHT: 0.15,
    REBOUNDING_WEIGHT: 0.1,
    DEFENSE_WEIGHT: 0.1,
    SPEED_WEIGHT: 0.05,
    DRIBBLING_TURNOVER_WEIGHT: 0.05,
} as const;

export const REBOUND = {
    OFFENSIVE_REBOUND_PROB: 0.2,
    DEFENSIVE_REBOUND_PROB: 0.8,
} as const;

export const FOUL = {
    BASE_SHOOTING_FOUL_PROB: 0.05,
    BASE_NON_SHOOTING_FOUL_PROB: 0.1,
    FREE_THROWS_PER_SHOOTING_FOUL: 2,
    FREE_THROWS_IF_AND_ONE: 1,
    BONUS_FOUL_THRESHOLD: 5,
} as const;

export const STAMINA = {
    FATIGUE_PER_POSSESSION: 0.5,
    RECOVERY_PER_BENCH_POSSESSION: 0.3,
    Performance_DROP_PER_FATIGUE: 0.02,
    MAX_FATIGUE: 100,
    SUBSTITUTION_THRESHOLD: 70,
} as const;

export const POINTS = {
    TWO_POINT_MADE: 2,
    THREE_POINT_MADE: 3,
    FREE_THROW_MADE: 1,
} as const;

export const SIM = {
    DEFAULT_SEED: 42,
    LOG_PLAY_BY_PLAY: true,
} as const;